### PR TITLE
Added excuses corpus

### PR DESCRIPTION
**Pull request by HalynaOlesiuk**
https://github.com/nltk/nltk_data/issues/97

### CODE REVIEW

**Comment by stevenbird** [comment]
@HalynaOlesiuk - is there a literature citation for this corpus? I.e. does it have a userbase?

**Comment by HalynaOlesiuk** [comment]
This corpus isn’t published anywhere.
This corpus comprises texts of political apologies which were published on different websites.
These texts with apologies are materials of the master’s research paper which I’m writing now.  

Apologies have also links to their sources in internet.

**Comment by HalynaOlesiuk** [comment]
Excuses include which communication tactics are used in text.

**Comment by stevenbird** [comment]
@HalynaOlesiuk: thanks again for your interest in contributing a corpus. We have decided to document our assumptions about corpus contributions on our wiki here:

https://github.com/nltk/nltk/wiki/Adding-a-Corpus

This means we have decided not to accept this contribution at present.

**Pull request closed without merging**
