### PR TITLE
Add Russian language for PunktSentenceTokenizer()

### PR DESCRIPTION
**Pull request by Mottl**
This commit adds Russian language support in `PunktSentenceTokenizer()`.
Data was taken from 3 sources:
– Articles from Russian Wikipedia (about 1 million sentences);
– Common Russian abbreviations from Russian orthographic dictionary, edited by V. V. Lopatin;
– Generated names initials.

After some research it was found that the single `params.abbrev_types` performs better than  together with `params.collocations` and `params.ortho_content`, so the latter were removed from the trained tokenizer.

### CODE REVIEW

**Comment by Mottl** [comment]
@stevenbird, please review

**Comment by Mottl** [comment]
@stevenbird, please review

**Comment by Hiyorimi** [comment]
@stevenbird please review this PR, because many great projects (like [sumy](https://github.com/miso-belica/sumy), for instance) rely on NLTK toolkit in solving NLP-tasks. 

I had to use sumy and in order to use it russian, I monkey patched nltk_data container with Mottl's repo content and everything started working brilliantly.

**Comment by karelin** [comment]
@stevenbird Russian language will be quite important improvement. Thanks!!!

**Comment by buriy** [comment]
@stevenbird do you need a test-case maybe? I assume the problem is to check whether the commit works for you.

**Comment by stevenbird** [comment]
@Mottl, cc @Hiyorimi, @karelin, @buriy:
thanks for your contribution and sorry for the long delay

**Comment by Hiyorimi** [comment]
Thank you!

**Pull request closed without merging**
