### PR TITLE
Add a Corpus for the names of medicines in india 

### PR DESCRIPTION
**Pull request by abeepathak96**
[drugs.txt](https://github.com/nltk/nltk_data/files/1050445/drugs.txt)
This is a text file that contains the names of medicines in India, which are prescribed in India by all the doctors this list is being constantly updated by our team. please add this list as a corpus in the nltk-data so that it can be used in the clinical data parsing.

### CODE REVIEW

**Comment by alvations** [comment]
Why is this file added to the non-breaking prefix?

**Comment by abeepathak96** [comment]
That is the list of names of medicines in India which I want to add in nltk
as a corpus so that drug named recognition can be performed

**Comment by alvations** [comment]
It should be added to another corpus and not not the `nonbreaking_prefixes`. Also, there are other steps that needs to be done to like updating the indices for the `all.xml`, `corpora.xml`, etc. 

If you're suggesting a new corpus, it should be an issue instead of a pull request (PR) =) https://github.com/nltk/nltk_data/issues 

I see that there's already an issue at nltk_data#77 , perhaps someone else would pick it up and add it to the `nltk_data`.

**Comment by stevenbird** [comment]
As noted in #77, we don't have capacity to add and maintain custom wordlists like this, sorry. They can be distributed outside of NLTK.

**Pull request closed without merging**
