### PR TITLE
add Dutch (nld) to omw corpus

### PR DESCRIPTION
**Pull request by wimmuskee**
downloaded the original file from http://compling.hss.ntu.edu.sg/omw/

### CODE REVIEW

**Comment by stevenbird** [comment]
@fcbond would you please advise on how you want to handle omw updates?

**Comment by alvations** [comment]
I think we can create a "recipe" script to update OMW zipballs, e.g.:

```bash
# Create a new direcotry to avoid clashes with the actual nltk_data directory 
# that the nltk code uses and also avoid clashes with old version of the nltk_data repo.
mkdir git-repos && cd git-repos

# Re-cloning the github, this might take some time.
git clone https://github.com/fcbond/nltk_data.git 

# Move the corpora subdirectory
cd /nltk_data/packages/corpora/

# Checkout the gh-pages branch
git checkout gh-pages

# Replace the omw.zip
rm omw.zip
wget http://compling.hss.ntu.edu.sg/omw/all.zip -O omw.zip 

# Recreate the index.xml
cd ../..
make

# Git add, commit, push.
git add packages/corpora/omw.zip
git add index.xml
git commit -m 'updated OMW data'
git push
```

But, I think it's better we wait for a new version of OMW when it's ready from @fcbond before we update the omw zipball in `nltk_data`.

**Comment by patvdleer** [comment]
I tried this but make runs into an error, I'm not sure why since the `omw.zip` contains `wns` followed by the directories for each language.

```
python tools/build_pkg_index.py . http://www.nltk.org/nltk_data/packages index.xml
Traceback (most recent call last):
  File "tools/build_pkg_index.py", line 24, in <module>
    index = build_index(ROOT, BASE_URL)
  File "/usr/local/lib/python2.7/dist-packages/nltk/downloader.py", line 2088, in build_index
    for pkg_xml, zf, subdir in _find_packages(os.path.join(root, 'packages')):
  File "/usr/local/lib/python2.7/dist-packages/nltk/downloader.py", line 2223, in _find_packages
    'single subdirectory %s/' % (uid, uid))
ValueError: Zipfile omw.zip does not expand to a single subdirectory omw/
Makefile:5: recipe for target 'pkg_index' failed
make: *** [pkg_index] Error 1
```

```bash
# Create a new direcotry to avoid clashes with the actual nltk_data directory 
# that the nltk code uses and also avoid clashes with old version of the nltk_data repo.
mkdir git-repos && cd git-repos

# Re-cloning the github, this might take some time.
git clone https://github.com/fcbond/nltk_data.git 

# move into repos
cd nltk_data/

# Checkout the gh-pages branch
git checkout gh-pages

# Move the corpora subdirectory
cd packages/corpora/

# Replace the omw.zip
rm omw.zip
wget http://compling.hss.ntu.edu.sg/omw/all.zip -O omw.zip 

# Recreate the index.xml
cd ../..
make
```

**Comment by patvdleer** [comment]
Renaming the `wns` directory to `omw` in the zip seems to fix this

**Comment by stevenbird** [comment]
@fcbond would you please review?

**Comment by stevenbird** [comment]
I merged it manually. Thanks @wimmuskee.
@patvdleer: thanks for the input; we can look into a generic solution if traffic increases...

**Pull request closed without merging**
