### PR TITLE
Fix index.xml typo breaking nltk.download

### PR DESCRIPTION
**Pull request by glowskir**
As per title

### CODE REVIEW

**Review by Alphadelta14 — APPROVED** [review]

**Review by Axik — APPROVED** [review]

**Review by goliney — APPROVED** [review]

**Review by Templarrr — APPROVED** [review]

**Review by IevgeniiB — APPROVED** [review]

**Review by andrew-qa — APPROVED** [review]

**Comment by Alphadelta14** [comment]
@stevenbird very important

**Review by alexeyraspopov — APPROVED** [review]

**Review by bmwant — CHANGES_REQUESTED** [review]
lol

**Comment by tilgalas** [comment]
temporary workaround:

instead of 

`python -m nltk.downloader corpus`

use 

`python -c "from nltk.downloader import Downloader; d = Downloader('https://raw.githubusercontent.com/nltk/nltk_data/1164703d436cad9e9cc082a59f9c9f10a7699ac8/index.xml'); d.download('corpus')"`

**Comment by rvause** [comment]
This should also work (using index from this branch)

`python -m nltk.downloader -u https://raw.githubusercontent.com/glowskir/nltk_data/7b505ff1f858a489e5b2d879573bdaaa8ef06732/index.xml corpus`

**Comment by alvations** [comment]
@stevenbird, sorry for merging this before you checking. #58 is breaking code on the user space.

**Comment by alvations** [comment]
Thanks guys for spotting this error! Sorry that it broke while merging the Dolch word list.

**Comment by simonrichard** [comment]
Sorry for making that mistake in the first place and thanks for fixing it so fast.

**Comment by stevenbird** [comment]
Thanks @alvations!

**Pull request merged**
